#ifndef __CPU_SYS_GLB_H__
#define __CPU_SYS_GLB_H__

#define COMMON_CPU_GLB_BASE				0x02330000
#define CA53_CFG_RVBARADDR0_H				(COMMON_CPU_GLB_BASE + 0x4)
#define CA53_CFG_RVBARADDR0_L				(COMMON_CPU_GLB_BASE + 0x8)
#define CA53_CFG_RVBARADDR1_H				(COMMON_CPU_GLB_BASE + 0xC)
#define CA53_CFG_RVBARADDR1_L				(COMMON_CPU_GLB_BASE + 0x10)

#define COMMON_SYS_GLB_BASE				0x02340000
#define COMMON_SYS_CLK_MUX_0_ADDR			(COMMON_SYS_GLB_BASE + 0x0)
#define COMMON_SYS_CLK_MUX_2_ADDR			(COMMON_SYS_GLB_BASE + 0x18)
#define EIC_EN_SET					(COMMON_SYS_GLB_BASE + 0x214)
#define EIC_EN_CLR					(COMMON_SYS_GLB_BASE + 0x218)
#define EIC_RISCV_EN					(COMMON_SYS_GLB_BASE + 0x248)
#define EIC_EN_MASK_ALL					0x7F
#define MISC_CTRL					(COMMON_SYS_GLB_BASE + 0x380)
#define MISC_CTRL_VAL					0x4
#define EIC_MASK_EN_SET					(COMMON_SYS_GLB_BASE + 0x198)
#define EIC_MASK_EN_CLR					(COMMON_SYS_GLB_BASE + 0x19C)

#define COMMON_SYS_FAB_TOP_GLB_BASE			0x2370000

#define COMM_SYS_DUMMY_SW0_CORE1_LOW			(COMMON_SYS_GLB_BASE + 0xDC) //second core jump addr [31:0]   //for core1 after wfe，low bit
#define COMM_SYS_DUMMY_SW1_CORE1_HIGH			(COMMON_SYS_GLB_BASE + 0xE0) //second core jump addr [39:32]  //for core1 after wfe，high bit

#define COMM_SYS_DUMMY_SW2_CORE0_LOW			(COMMON_SYS_GLB_BASE + 0xE4) //second core jump addr [31:0]   //for core0 after wfe，low bit
#define COMM_SYS_DUMMY_SW3_CORE0_HIGH			(COMMON_SYS_GLB_BASE + 0xE8) //second core jump addr [39:32]  //for core0 after wfe，high bit

#define COMMON_SYS_COMMON2_DDR_BUS_IDLE_SW_ADDR		(COMMON_SYS_GLB_BASE + 0x490)
#define BIT_COMMON_SYS_COMMON2_DDR_BUS_IDLE_SW		BIT(0)

#define COMMON_SYS_COMMON2_DDR_BUS_IDLE_MASK_ADDR	(COMMON_SYS_GLB_BASE + 0x494)
#define BIT_COOMON_SYS_COMMON2_DDR_BUS_IDLE_MASK	BIT(0)

#define COMMON_SYS_PAD_SLEEP_BYP_ADDR			(COMMON_SYS_GLB_BASE + 0x188)
#define COMMON_SYS_PLL_SLEEP_BYP_ADDR			(COMMON_SYS_GLB_BASE + 0x18C)
#define COMMON_SYS_XTAL_SLEEP_BYP_ADDR			(COMMON_SYS_GLB_BASE + 0x190)

#define COMMON_SYS_EIC_MASK_ENABLE_SET_ADDR		(COMMON_SYS_GLB_BASE + 0x198)
#define BIT_COMMON_SYS_EIC_MASK_ENABLE_SET		BIT(0)
#define COMMON_SYS_EIC_RISCV_MASK_ENABLE_SET_ADDR 	(COMMON_SYS_GLB_BASE + 0x1A4)
#define BIT_COMMON_SYS_EIC_RISCV_MASK_ENABLE_SET	BIT(0)

#define COMMON_SYS_DEB_GPIO_31_0_INT_CLR_SET_ADDR	(COMMON_SYS_GLB_BASE + 0x15C)
#define COMMON_SYS_DEB_GPIO_31_0_INT_MASK_SET_ADDR	(COMMON_SYS_GLB_BASE + 0x138)
#define COMMON_SYS_DEB_GPIO_31_0_INT_MASK_CLR_ADDR	(COMMON_SYS_GLB_BASE + 0x13C)
#define COMMON_SYS_DEB_GPIO_63_32_INT_CLR_SET_ADDR	(COMMON_SYS_GLB_BASE + 0x150)
#define COMMON_SYS_DEB_GPIO_63_32_INT_MASK_SET_ADDR	(COMMON_SYS_GLB_BASE + 0x12C)
#define COMMON_SYS_DEB_GPIO_63_32_INT_MASK_CLR_ADDR	(COMMON_SYS_GLB_BASE + 0x130)
#define COMMON_SYS_DEB_GPIO_89_64_INT_CLR_SET_ADDR	(COMMON_SYS_GLB_BASE + 0x144)
#define COMMON_SYS_DEB_GPIO_89_64_INT_MASK_SET_ADDR	(COMMON_SYS_GLB_BASE + 0x120)
#define COMMON_SYS_DEB_GPIO_89_64_INT_MASK_CLR_ADDR	(COMMON_SYS_GLB_BASE + 0x124)
#define BIT_COMMON_SYS_DEB_GPIO_MASK_ALL		0xffffffff

#define COMMON_SYS_DEB_GPIO_LP_INT_CLR0_SET_ADDR	(COMMON_SYS_GLB_BASE + 0x2F4)
#define COMMON_SYS_DEB_GPIO_LP_INT_CLR1_SET_ADDR	(COMMON_SYS_GLB_BASE + 0x328)
#define COMMON_SYS_DEB_GPIO_LP_INT_CLR2_SET_ADDR	(COMMON_SYS_GLB_BASE + 0x35C)

#define COMMON_SYS_USB_INT_CTRL_SET_ADDR		(COMMON_SYS_GLB_BASE + 0x3F8)
#define BIT_COMMON_SYS_USB_WAKE_UP_INT_MASK_SET		BIT(1)
#define BIT_COMMON_SYS_USB_WAKE_UP_INT_CLR_SET		BIT(0)

#define COMMON_SYS_AUX_CFG1_CLR_ADDR		(COMMON_SYS_GLB_BASE + 0x1C0)
#define COMMON_SYS_AUX_CFG1_SET_ADDR		(COMMON_SYS_GLB_BASE + 0x1BC)

/* timer32 config */
#define COMMON_SYS_EIC_EN_SET_ADDR			(COMMON_SYS_GLB_BASE + 0x214)
#define BIT_COMMON_TMR32_EIC_EN_SET			BIT(1)
#define COMMON_SYS_SW_RST_0_ADDR			(COMMON_SYS_GLB_BASE + 0x54)
#define BIT_COMMON_SYS_TIMER32_SW_RST			BIT(22)
#define BIT_COMMON_SYS_TIMER32_SW_PRST			BIT(21)
#define COMMON_SYS_CLK_MUX1_ADDR			(COMMON_SYS_GLB_BASE + 0xc)
#define BIT_COMMON_SYS_CLK_TIMER32_SEL_24M		BIT(26)
#define COMMON_SYS_CLK_EB_0_ADDR			(COMMON_SYS_GLB_BASE + 0x24)
#define BIT_COMMON_SYS_CLK_TIMER32_EB			BIT(14)
#define COMMON_SYS_CLK_EB_1_ADDR			(COMMON_SYS_GLB_BASE + 0x30)
#define BIT_COMMON_SYS_PCLK_TMR32_EB			BIT(15)
#define COMMON_SYS_XTAL_SLEEP_BYP_ADDR			(COMMON_SYS_GLB_BASE + 0x190)

#endif
