#ifndef __CPU_SYS_H_
#define __CPU_SYS_H_
#include <sys_all_have.h>
#include <pmu.h>
#define CPU_SYS_GLB_BASE_ADDR				0x1900000
#define CPU_SYS_CLK_MUX_0_ADDR				(CPU_SYS_GLB_BASE_ADDR + 0x0)
#define CPU_SYS_CLK_EB_0_ADDR				(CPU_SYS_GLB_BASE_ADDR + 0x04)
#define CPU_SYS_CLK_EB_1_ADDR				(CPU_SYS_GLB_BASE_ADDR + 0x08)
#define CPU_SYS_CLK_DIV_0_ADDR				(CPU_SYS_GLB_BASE_ADDR + 0x0C)
#define CPU_SYS_INT_MSK_SET_ADDR			(CPU_SYS_GLB_BASE_ADDR + 0x10D0)
#define BIT_CPU_SYS_CA53_CLUSTER_INT_DISABLE_SET 	BIT(0)
#define BIT_CPU_SYS_CA53_CPU_INT_DISABLE_SET		(3 << 4)
#define CPU_SYS_INT_MSK_CLR_ADDR			(CPU_SYS_GLB_BASE_ADDR + 0x20D0)
#define BIT_CPU_SYS_CA53_CLUSTER_INT_DISABLE_CLR	BIT(0)
#define BIT_CPU_SYS_CA53_CPU_INT_DISABLE_CLR		(3 << 4)
#define CPU_SYS_CLK_EB_1_CLR_ADDR			(CPU_SYS_GLB_BASE_ADDR + 0x2008)
#define BIT_CPU_SYS_PCLK_CPU_DBGMNR_EB_CLR		BIT(9)
#define BIT_CPU_SYS_ACLK_CPU_DBGMNR_EB_CLR		BIT(0)
#define BIT_CPU_SYS_PCLK_CPU_PERFMNR_EB_CLR		BIT(10)
#define BIT_CPU_SYS_ACLK_CPU_PERFMNR_EB_CLR		BIT(1)
#define BIT_CPU_SYS_CLK_PERFMNR_24M_EB_CLR		BIT(6)
#define BIT_CPU_SYS_HCLK_SPI_EB_CLR			BIT(8)
#define BIT_CPU_SYS_CLK_EMMC_EB_CLR			BIT(4)
#define BIT_CPU_SYS_CLK_ROSC_EB_CLR			BIT(7)
#define CPU_SYS_CLK_EB_0_CLR_ADDR			(CPU_SYS_GLB_BASE_ADDR + 0x2004)
#define BIT_CPU_SYS_CLK_H_SSI_EB_CLR			BIT(3)
#define BIT_CPU_SYS_CLK_EMMC_CARD_EB_CLR		BIT(2)
#define BIT_CPU_SYS_CLK_BROM_EB_CLR			BIT(0)

#define CPU_SYS_LPC_CFG_2_SET_ADDR			(CPU_SYS_GLB_BASE_ADDR + 0x10F8)
#define BIT_CPU_SYS_SLP_EN_SET 				BIT(0)
#define BIT_CPU_SYS_DATA_IDLE_EN_SET			BIT(2)
#define CPU_SYS_LPC_CFG_1_SET_ADDR			(CPU_SYS_GLB_BASE_ADDR + 0x10F4)
#define BIT_CPU_SYS_DATA_BUS_IDLE_EN_SET 		BIT(0)
#define BIT_CPU_SYS_DATA_NOC_TIMEOUT_EN_SET		BIT(3)
#define CPU_SYS_LPC_CFG_0_SET_ADDR			(CPU_SYS_GLB_BASE_ADDR + 0x10F0)
#define BIT_CPU_SYS_CFG_BUS_IDLE_EN_SET			BIT(0)
#define BIT_CPU_SYS_CFG_NOC_TIMEOUT_EN_SET		BIT(3)
#define CPU_SYS_RSP2INT_CTRL_SET_ADDR			(CPU_SYS_GLB_BASE_ADDR + 0x1124)
#define BITS_CPU_ERR_INT_CLEAR_SET			(3 << 0)


#define BIT_CPU_SYS_CFG_BUS_IDLE_EN_CLR			BIT(0)
#define BIT_CPU_SYS_CFG_NOC_TIMEOUT_EN_CLR		BIT(3)
#define CPU_SYS_LPC_CFG_0_CLR_ADDR			(CPU_SYS_GLB_BASE_ADDR + 0x20F0)
#define BIT_CPU_SYS_DATA_BUS_IDLE_EN_CLR		BIT(0)
#define BIT_CPU_SYS_DATA_NOC_TIMEOUT_EN_CLR		BIT(3)
#define CPU_SYS_LPC_CFG_1_CLR_ADDR			(CPU_SYS_GLB_BASE_ADDR + 0x20F4)

#define CPU_SYS_LPC_CFG_2_CLR_ADDR			(CPU_SYS_GLB_BASE_ADDR + 0x20F8)
#define BIT_CPU_SYS_SLP_EN_CLR 				BIT(0)
#define BIT_CPU_SYS_DATA_IDLE_EN_CLR			BIT(2)

#define CPU_SYS_FAB_GT_CTRL0_ADDR			(CPU_SYS_GLB_BASE_ADDR + 0x104)
#define CPU_SYS_FAB_GT_CTRL0_VAL			BIT(0)

int cpu_sys_sleep(void);
int cpu_sys_helper(void);
#endif
