#ifndef __DDR_SYS_H_
#define __DDR_SYS_H_
#include <sys_all_have.h>
#include <ax620e_common_sys_glb.h>
#include <cpu_sys.h>

#define REG_R32(ADDR)				(*(volatile int *) (ADDR))
#define REG_W32(ADDR, DATA)			((*(volatile int *) (ADDR)) = (DATA))

#define DDR_SYS_GLB_BASE_ADDR			0x210000

#define DDRC_GLB_BASE_ADDR			0x100000

#define DPLL_GLB_BASE_ADDR			0x265000
#define DPLL_ON_CFG_CLR_ADDR			(DPLL_GLB_BASE_ADDR + 0x4C)
#define BITS_DPLL_ON_CFG_CLR			(0xff << 9)
#define DPLL_PLL_RE_OPEN_ADDR			(DPLL_GLB_BASE_ADDR + 0x68)

#define DDR_SYS_AXICLK_OFF_SET_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x180)
#define BIT_DDR_SYS_AXICLK_OFF_HW_EN_SET	BIT(1)

#define DDR_SYS_AXICLK_OFF_CLR_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x184)
#define BIT_DDR_SYS_AXICLK_OFF_HW_EN_CLR	BIT(1)

#define DDR_SYS_CORECLK_OFF_SET_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x188)
#define BIT_DDR_SYS_CORECLK_OFF_HW_EN_SET	BIT(1)

#define DDR_SYS_CORECLK_OFF_CLR_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x18C)
#define BIT_DDR_SYS_CORECLK_OFF_HW_EN_CLR	BIT(1)

#define DDR_SYS_CLK_EB_0_ADDR			(DDR_SYS_GLB_BASE_ADDR + 0x4)
#define DDR_SYS_CLK_EB_1_ADDR			(DDR_SYS_GLB_BASE_ADDR + 0x8)
#define DDR_SYS_CLK_EB_2_ADDR			(DDR_SYS_GLB_BASE_ADDR + 0xC)

#define DDR_SYS_CLK_EB_0_SET_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0xD8)

#define DDR_SYS_CLK_EB_0_CLR_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0xDC)

#define DDR_SYS_CLK_EB_1_SET_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0xE0)
#define BIT_DDR_SYS_CLK_EB_1_PCLK_DFI_MNR_EB	BIT(30)

#define DDR_SYS_CLK_EB_1_CLR_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0xE4)

#define DDR_SYS_CLK_EB_2_SET_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0xE8)
#define BIT_PCLK_FW_OTHERS_EB_SET		BIT(1)
#define BIT_PCLK_FW_NPU_EB_SET			BIT(0)

#define DDR_SYS_CLK_EB_2_CLR_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0xEC)
#define BIT_PCLK_FW_OTHERS_EB_CLR		BIT(1)
#define BIT_PCLK_FW_NPU_EB_CLR			BIT(0)

#define DDR_SYS_DPLL_BASE_ADDR			0x265000
#define DDR_SYS_PLL_RDY_STS_ADDR		(DDR_SYS_DPLL_BASE_ADDR + 0x40)
#define BIT_DDR_STS_DPLL_RSY			BIT(0)

#define DDR_SYS_DDRC_WAKEUP_SET_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x168)
#define BIT_DDR_SYS_DDRC_WAKEUP_SW_SET		BIT(0)

#define DDR_SYS_DDRC_WAKEUP_CLR_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x16C)
#define BIT_DDR_SYS_DDRC_WAKEUP_SW_CLR		BIT(0)

#define DDR_SYS_DDR_DEEP_SLEEP_LATCH_CLR_ADDR	(DDR_SYS_GLB_BASE_ADDR + 0xAC)
#define BIT_DDR_SYS_DPLL_LPC_OFF_CLR		BIT(1)

#define DDR_SYS_LPC_DATA_SET_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x170)
#define BIT_DDR_SYS_LPC_DATA_BUS_IDLE_EN_SET	BIT(0)

#define DDR_SYS_LPC_DATA_CLR_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x174)
#define BIT_DDR_SYS_LPC_DATA_BUS_IDLE_EN_CLR	BIT(0)

#define DDR_SYS_SLP_IGNORE_CPU_SET_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x178)
#define BIT_DDR_SYS_SLP_IGNORE_CPU_EN_SET	BIT(0)

#define DDR_SYS_SLP_IGNORE_CPU_CLR_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x17C)
#define BIT_DDR_SYS_SLP_IGNORE_CPU_EN_CLR	BIT(0)

#define DDR_SYS_DDR_AXI_SET_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x158)
#define BITS_DDR_SYS_DDR_AXI_LP_REQ_SET		(0x1F << 0)

#define DDR_SYS_DDR_AXI_CLR_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x15C)
#define BITS_DDR_SYS_DDR_AXI_LP_REQ_CLR		(0x1F << 0)

#define DDR_SYS_DDRC_SLP_SET_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x160)
#define BIT_DDR_SYS_DDRC_SLP_SW_SET		BIT(0)

#define DDR_SYS_DDRC_SLP_CLR_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x164)
#define BIT_DDR_SYS_DDRC_SLP_SW_CLR		BIT(0)

#define DDR_SYS_LP_DDRC_ADDR			(DDR_SYS_GLB_BASE_ADDR + 0x80)
#define BITS_DDR_SYS_LP_DDRC_STATE		(0x3F << 0)
#define DDR_SYS_LP_DDRC_ENTER_LIGHT_SLP		0x23
#define DDR_SYS_LP_DDRC_EXIT_LIGHT_SLP		0x0

#define DDR_SYS_DDR_DEEP_SLP_LATCH_CLR_SET_ADDR	(DDR_SYS_GLB_BASE_ADDR + 0x208)
#define BIT_DDR_SYS_DDRPHY_PD_LATCH_CLR_SET	BIT(0)

#define DDR_SYS_DDR_DEEP_SLP_LATCH_CLR_CLR_ADDR	(DDR_SYS_GLB_BASE_ADDR + 0x20C)
#define BIT_DDR_SYS_DDRPHY_PD_LATCH_CLR_CLR	BIT(0)

#define DDR_SYS_CLKG_BYPASS_SET_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x150)
#define BIT_DDR_SYS_CLKG_BYPASS_DDRC_REF_SET	BIT(3)
#define BIT_DDR_SYS_CLKG_BYPASS_AXI_SET		BIT(2)
#define BIT_DDR_SYS_CLKG_BYPASS_DDRPHY_SET	BIT(1)
#define BIT_DDR_SYS_CLKG_BYPASS_DDRC_SET	BIT(0)
#define DDR_SYS_CLKG_BYPASS_CLR_ADDR		(DDR_SYS_GLB_BASE_ADDR + 0x154)
#define BIT_DDR_SYS_CLKG_BYPASS_DDRC_REF_CLR	BIT(3)
#define BIT_DDR_SYS_CLKG_BYPASS_AXI_CLR		BIT(2)
#define BIT_DDR_SYS_CLKG_BYPASS_DDRPHY_CLR	BIT(1)
#define BIT_DDR_SYS_CLKG_BYPASS_DDRC_CLR	BIT(0)

#define DDRC_DDRMC_PORT0_CFG0_ADDR		(DDRC_GLB_BASE_ADDR + 0x0)
#define BIT_DDRC_RF_AUTO_SLP_EN_PORT0		BIT(16)

#define DDRC_DDRMC_PORT1_CFG0_ADDR		(DDRC_GLB_BASE_ADDR + 0x10)
#define BIT_DDRC_RF_AUTO_SLP_EN_PORT1		BIT(16)

#define DDRC_DDRMC_PORT2_CFG0_ADDR		(DDRC_GLB_BASE_ADDR + 0x20)
#define BIT_DDRC_RF_AUTO_SLP_EN_PORT2		BIT(16)

#define DDRC_DDRMC_PORT3_CFG0_ADDR		(DDRC_GLB_BASE_ADDR + 0x30)
#define BIT_DDRC_RF_AUTO_SLP_EN_PORT3		BIT(16)

#define DDRC_DDRMC_PORT4_CFG0_ADDR		(DDRC_GLB_BASE_ADDR + 0x40)
#define BIT_DDRC_RF_AUTO_SLP_EN_PORT4		BIT(16)

#define DDRC_DDRMC_CFG22_ADDR			(DDRC_GLB_BASE_ADDR + 0xD8)
#define BIT_DDRC_RF_AUTO_SLP_EN			BIT(0)

int ddr_sys_sleep(void);
int ddr_sys_wakeup(void);
int ddr_sys_helper(void);
#endif
