#ifndef __DEB_GPIO_H_
#define __DEB_GPIO_H_
#define PINMUX_G6_BASE_ADDR	0x2304000
#define PINMUX_G6_MISC_SET_ADDR (PINMUX_G6_BASE_ADDR + 0xA8)
#define PINMUX_G6_CTRL_SET_SET	BIT(0)
#define PINMUX_G6_MISC_CLR_ADDR (PINMUX_G6_BASE_ADDR + 0xAC)
#define PINMUX_G6_CTRL_CLR_CLR	BIT(0)
#endif