#ifndef __FLASH_SYS_H_
#define __FLASH_SYS_H_
#include <sys_all_have.h>
#include <pmu.h>

#define FLASH_SYS_GLB_BASE_ADDR			0x10030000
#define FLASH_SYS_CLK_MUX_0_ADDR		(FLASH_SYS_GLB_BASE_ADDR + 0x0)
#define FLASH_SYS_CLK_EB_0_ADDR			(FLASH_SYS_GLB_BASE_ADDR + 0x4)
#define BITS_FLASH_SYS_CLK_EB_0			(1 << 5)
#define FLASH_SYS_CLK_EB_1_ADDR			(FLASH_SYS_GLB_BASE_ADDR + 0x8)
#define BITS_FLASH_SYS_CLK_EB_1			0x00800
#define FLASH_SYS_CLK_DIV_0_ADDR		(FLASH_SYS_GLB_BASE_ADDR + 0xC)
#define FLASH_SYS_CLK_DIV_1_ADDR		(FLASH_SYS_GLB_BASE_ADDR + 0x10)

#define FLASH_SYS_LPC_CFG_ADDR			(FLASH_SYS_GLB_BASE_ADDR + 0x148)
#define BIT_FLASH_LPC_CFG_BUS_IDLE		BIT(26)
#define FLASH_SYS_LPC_CFG_SET_ADDR		(FLASH_SYS_GLB_BASE_ADDR + 0x4148)
#define BIT_FLASH_LPC_CFG_BUS_IDLE_EN_SET	BIT(0)
#define FLASH_SYS_LPC_DATA_ADDR			(FLASH_SYS_GLB_BASE_ADDR + 0x14C)
#define BIT_FLASH_LPC_DATA_BUS_FRC_WORK		BIT(2)
#define BIT_FLASH_LPC_DATA_BUS_IDLE		BIT(26)
#define FLASH_SYS_FAB_BUSY_ADDR			(FLASH_SYS_GLB_BASE_ADDR + 0x178)
#define FLASH_SYS_LPC_DATA_SET_ADDR		(FLASH_SYS_GLB_BASE_ADDR + 0x414C)
#define BIT_FLASH_LPC_DATA_BUS_IDLE_EN_SET	BIT(0)
#define FLASH_SYS_LPC_SET_ADDR			(FLASH_SYS_GLB_BASE_ADDR + 0x4150)
#define BIT_FLASH_LPC_SLP_EN_SET		BIT(2)
#define BIT_FLASH_LPC_DATA_IDLE_EN_SET		BIT(3)
#define BIT_FLASH_LPC_BP_CLK_EB_SET		BIT(0)
#define FLASH_SYS_LPC_CLR_ADDR			(FLASH_SYS_GLB_BASE_ADDR + 0x8150)
#define BIT_FLASH_LPC_SLP_EN_CLR		BIT(2)
#define FLASH_SYS_LPC_CFG_CLR_ADDR		(FLASH_SYS_GLB_BASE_ADDR + 0x8148)
#define BIT_FLASH_LPC_CFG_BUS_IDLE_EN_CLR	BIT(0)
#define FLASH_SYS_LPC_DATA_CLR_ADDR		(FLASH_SYS_GLB_BASE_ADDR + 0x814C)
#define BIT_FLASH_LPC_DATA_BUS_IDLE_EN_CLR	BIT(0)
#define FLASH_SYS_LPC_CLR_ADDR			(FLASH_SYS_GLB_BASE_ADDR + 0x8150)
#define BIT_FLASH_LPC_SLP_EN_CLR		BIT(2)
#define BIT_FLASH_LPC_DATA_IDLE_EN_CLR		BIT(3)

int flash_sys_sleep(void);
int flash_sys_wakeup(void);
#endif
