#ifndef __ISP_SYS_H_
#define __ISP_SYS_H_
#include <sys_all_have.h>
#include <pmu.h>

#define ISP_SYS_GLB_BASE_ADDR			0x2500000
#define ISP_SYS_CLK_MUX_0_ADDR			(ISP_SYS_GLB_BASE_ADDR + 0x0)
#define ISP_SYS_CLK_EB_0_ADDR			(ISP_SYS_GLB_BASE_ADDR + 0x4)
#define BITS_ISP_CLK_EB_0			0x08
#define ISP_SYS_CLK_EB_1_ADDR			(ISP_SYS_GLB_BASE_ADDR + 0x8)
#define BITS_ISP_CLK_EB_1			0x8

#define ISP_SYS_LPC_DATA_SET_ADDR		(ISP_SYS_GLB_BASE_ADDR + 0x100)
#define BIT_ISP_LPC_DATA_BUS_IDLE_EN_SET	BIT(2)
#define ISP_SYS_LPC_CFG_SET_ADDR		(ISP_SYS_GLB_BASE_ADDR + 0x110)
#define BIT_ISP_LPC_CFG_BUS_IDLE_EN_SET		BIT(2)
#define ISP_SYS_LPC_DATA_SET_ADDR		(ISP_SYS_GLB_BASE_ADDR + 0x100)
#define BIT_ISP_LPC_DATA_IDLE_EN_SET		BIT(3)
#define ISP_SYS_SW_RST_1_CLR_ADDR		(ISP_SYS_GLB_BASE_ADDR + 0xEC)
#define BIT_ISP_SYS_LPC_SW_RST_CLR		BIT(18)

#define ISP_SYS_SLEEP_EN_SET_ADDR		(ISP_SYS_GLB_BASE_ADDR + 0xF8)
#define BIT_ISP_SLEEP_EN_SET			BIT(1)

#define ISP_SYS_LPC_DATA_CLR_ADDR		(ISP_SYS_GLB_BASE_ADDR + 0x104)
#define BIT_ISP_LPC_DATA_BUS_IDLE_EN_CLR	BIT(2)
#define ISP_SYS_LPC_CFG_CLR_ADDR		(ISP_SYS_GLB_BASE_ADDR + 0x114)
#define BIT_ISP_LPC_CFG_BUS_IDLE_EN_CLR		BIT(2)
#define ISP_SYS_LPC_DATA_CLR_ADDR		(ISP_SYS_GLB_BASE_ADDR + 0x104)
#define BIT_ISP_LPC_DATA_BUS_IDLE_EN_CLR	BIT(2)
#define BIT_ISP_LPC_DATA_IDLE_EN_CLR		BIT(3)
#define ISP_SYS_SLEEP_EN_CLR_ADDR		(ISP_SYS_GLB_BASE_ADDR + 0xFC)
#define BIT_ISP_SLEEP_EN_CLR			BIT(1)


int isp_sys_sleep(void);
int isp_sys_wakeup(void);
#endif
