#ifndef __MM_SYS_H_
#define __MM_SYS_H_
#include <sys_all_have.h>
#include <pmu.h>
#define MM_SYS_GLB_BASE_ADDR		0x4430000
#define MM_SYS_CLK_MUX_0_ADDR		(MM_SYS_GLB_BASE_ADDR + 0x0)
#define MM_SYS_CLK_EB_0_ADDR		(MM_SYS_GLB_BASE_ADDR + 0x4)
#define BITS_MM_SYS_CLK_EB_0		0x8
#define MM_SYS_CLK_EB_1_ADDR		(MM_SYS_GLB_BASE_ADDR + 0x8)
#define BITS_MM_SYS_CLK_EB_1		0x400
#define MM_SYS_CLK_DIV_0_ADDR		(MM_SYS_GLB_BASE_ADDR + 0xC)
#define MM_SYS_LPC1_SET_ADDR		(MM_SYS_GLB_BASE_ADDR + 0x17C)
#define BIT_MM_LPC_CFG_BUS_IDLE_EN_SET	BIT(0)
#define MM_SYS_LPC2_SET_ADDR		(MM_SYS_GLB_BASE_ADDR + 0x184)
#define BIT_MM_LPC_DATA_BUS_IDLE_EN_SET	BIT(0)
#define MM_SYS_LPC0_SET_ADDR		(MM_SYS_GLB_BASE_ADDR + 0x174)
#define BIT_MM_LPC_SLP_EN_SET		BIT(0)
#define BIT_MM_DATA_IDLE_EN_SET		BIT(3)
#define MM_SYS_SW_RST_0_CLR_ADDR	(MM_SYS_GLB_BASE_ADDR + 0xc8)
#define BIT_MM_SYS_LPC_SW_RST_CLR	BIT(18)
#define MM_SYS_LPC1_CLR_ADDR		(MM_SYS_GLB_BASE_ADDR + 0x180)
#define BIT_MM_LPC_CFG_BUS_IDLE_EN_CLR	BIT(0)
#define MM_SYS_LPC2_CLR_ADDR		(MM_SYS_GLB_BASE_ADDR + 0x188)
#define BIT_MM_LPC_DATA_BUS_IDLE_EN_CLR	BIT(0)
#define MM_SYS_LPC0_CLR_ADDR		(MM_SYS_GLB_BASE_ADDR + 0x178)
#define BIT_MM_LPC_SLP_EN_CLR		BIT(0)
#define BIT_MM_DATA_IDLE_EN_CLR		BIT(3)
int mm_sys_sleep(void);
int mm_sys_wakeup(void);
#endif