#ifndef __NPU_SYS_H_
#define __NPU_SYS_H_
#include <sys_all_have.h>
#include <pmu.h>
#define NPU_SYS_GLB_BASE_ADDR			0x3890000
#define NPU_SYS_CLK_MUX_0_ADDR			(NPU_SYS_GLB_BASE_ADDR + 0x0)
#define NPU_SYS_CLK_EB_0_ADDR			(NPU_SYS_GLB_BASE_ADDR + 0x4)
#define BITS_NPU_SYS_CLK_EB_0			0x1
#define NPU_SYS_CLK_EB_1_ADDR			(NPU_SYS_GLB_BASE_ADDR + 0x8)
#define BITS_NPU_SYS_CLK_EB_1			0x2
#define NPU_SYS_LPC_CFG_SETTING_SET_ADDR	(NPU_SYS_GLB_BASE_ADDR + 0x84)
#define BIT_NPU_SYS_CFG_BUS_IDLE_EN_SET		BIT(0)
#define NPU_SYS_LPC_DATA_SETTING_SET_ADDR	(NPU_SYS_GLB_BASE_ADDR + 0x8C)
#define BIT_NPU_SYS_DATA_BUS_IDLE_EN_SET	BIT(0)
#define NPU_SYS_LPC_SETTING_SET_ADDR		(NPU_SYS_GLB_BASE_ADDR + 0x7C)
#define BIT_NPU_SYS_SLP_EN_SET			BIT(0)
#define BIT_NPU_SYS_DATA_IDLE_EB_SET		BIT(3)
#define NPU_SYS_SW_RST_0_CLR_ADDR		(NPU_SYS_GLB_BASE_ADDR + 0x78)
#define BIT_NPU_SYS_LPC_SW_RST_CLR		BIT(0)
#define NPU_SYS_EU_IDLE_STS_ADDR		(NPU_SYS_GLB_BASE_ADDR + 0x48)
#define NPU_SYS_LPC_CFG_SETTING_CLR_ADDR	(NPU_SYS_GLB_BASE_ADDR + 0x88)
#define BIT_NPU_SYS_CFG_BUS_IDLE_EN_CLR		BIT(0)
#define NPU_SYS_LPC_DATA_SETTING_CLR_ADDR	(NPU_SYS_GLB_BASE_ADDR + 0x90)
#define BIT_NPU_SYS_DATA_BUS_IDLE_EN_CLR	BIT(0)
#define NPU_SYS_LPC_SETTING_CLR_ADDR		(NPU_SYS_GLB_BASE_ADDR + 0x80)
#define BIT_NPU_SYS_SLP_EN_CLR			BIT(0)
#define BIT_NPU_SYS_DATA_IDLE_EB_CLR		BIT(3)
int npu_sys_sleep(void);
int npu_sys_wakeup(void);
#endif
