#ifndef __PERIPH_SYS_H_
#define __PERIPH_SYS_H_
#include <sys_all_have.h>
#include <pmu.h>
#define PERIPH_SYS_GLB_BASE_ADDR			0x4870000
#define PERIPH_SYS_CLK_MUX_0_ADDR			(PERIPH_SYS_GLB_BASE_ADDR + 0x00)
#define PERIPH_SYS_CLK_EB_0_ADDR			(PERIPH_SYS_GLB_BASE_ADDR + 0x04)
#define PERIPH_SYS_CLK_EB_0_CLR_ADDR			(PERIPH_SYS_GLB_BASE_ADDR + 0xB4)
#define BITS_PERIPH_SYS_CLK_EB_0			(0x37FDF) /* dont't clr clk_periph_24m and clk_wdt2_eb */
#define PERIPH_SYS_CLK_EB_1_ADDR			(PERIPH_SYS_GLB_BASE_ADDR + 0x08)
#define BITS_PERIPH_SYS_CLK_EB_1			(1 << 18)
#define PERIPH_SYS_CLK_EB_2_ADDR			(PERIPH_SYS_GLB_BASE_ADDR + 0x0C)
#define BITS_PERIPH_SYS_CLK_EB_2			0x0
#define PERIPH_SYS_CLK_EB_3_ADDR			(PERIPH_SYS_GLB_BASE_ADDR + 0x10)
#define BITS_PERIPH_SYS_CLK_EB_3			0x0
#define PERIPH_SYS_CLK_DIV_0_ADDR			(PERIPH_SYS_GLB_BASE_ADDR + 0x14)
#define PERIPH_SYS_LPC_CFG_SET_ADDR			(PERIPH_SYS_GLB_BASE_ADDR + 0x178)
#define BIT_PERIPH_SYS_LPC_CFG_BUS_IDLE_EN_SET		BIT(0)
#define PERIPH_SYS_LPC_CFG_CLR_ADDR			(PERIPH_SYS_GLB_BASE_ADDR + 0x17C)
#define BIT_PERIPH_SYS_LPC_CFG_BUS_IDLE_EN_CLR		BIT(0)
#define PERIPH_SYS_LPC_DATA_SET_ADDR			(PERIPH_SYS_GLB_BASE_ADDR + 0x180)
#define BIT_PERIPH_SYS_LPC_DATA_BUS_IDLE_EN_SET		BIT(0)
#define BIT_PERIPH_SYS_LPC_DATA_BUS_FRC_WORK_SET	BIT(2)
#define PERIPH_SYS_LPC_DATA_CLR_ADDR			(PERIPH_SYS_GLB_BASE_ADDR + 0x184)
#define BIT_PERIPH_SYS_LPC_DATA_BUS_IDLE_EN_CLR		BIT(0)
#define BIT_PERIPH_SYS_LPC_DATA_BUS_FRC_WORK_CLR	BIT(2)
#define PERIPH_SYS_LPC_SET_ADDR				(PERIPH_SYS_GLB_BASE_ADDR + 0x188)
#define BIT_PERIPH_SYS_LPC_SLP_EN_SET			BIT(16)
#define BIT_PERIPH_SYS_LPC_DATA_IDLE_EN_SET		BIT(24)
#define BIT_PERIPH_SYS_LPC_BP_CLK_EB_SET		BIT(0)
#define PERIPH_SYS_LPC_CLR_ADDR				(PERIPH_SYS_GLB_BASE_ADDR + 0x18C)
#define BIT_PERIPH_SYS_LPC_SLP_EN_CLR			BIT(16)
#define BIT_PERIPH_SYS_LPC_DATA_IDLE_EN_CLR		BIT(24)
#define PERIPH_SYS_SW_RST_1_CLR_ADDR			(PERIPH_SYS_GLB_BASE_ADDR + 0xE4)
#define BIT_PERIPH_SYS_LPC_SW_RST_CLR			BIT(14)
int peri_sys_sleep(void);
int peri_sys_wakeup(void);
#endif
