#ifndef __PLL_H_
#define __PLL_H_
#define PLL_GLB_REG_BASE		0x2210000
#define PLL_GRP_PLL_FRC_EN_SW_SET_ADDR	(PLL_GLB_REG_BASE + 0x228)
#define BIT_PLL_GRP_PLL_FRC_EN_SW_SET	0x1
#define PLL_GRP_PLL_FRC_EN_SET_ADDR	(PLL_GLB_REG_BASE + 0x21C)
#define BIT_PLL_GRP_PLL_FRC_EN_SET	0x1
#define PLL_CPLL_ON_CFG_CLR_ADDR	(PLL_GLB_REG_BASE + 0x1CC)
#define BITS_PLL_CPLL_ON_CFG_CLR	(0xffffff << 1)
#define PLL_CPUPLL_ON_CFG_CLR_ADDR	(PLL_GLB_REG_BASE + 0x1F0)
#define BITS_PLL_CPUPLL_ON_CFG_CLR	(0xff << 9)
#define PLL_EPLL_ON_CFG_CLR_ADDR	(PLL_GLB_REG_BASE + 0x1FC)
#define BITS_PLL_EPLL_ON_CFG_CLR	(0xff << 9)
#define PLL_HPLL_ON_CFG_CLR_ADDR	(PLL_GLB_REG_BASE + 0x214)
#define BITS_PLL_HPLL_ON_CFG_CLR	(0xff << 9)
#define PLL_NPLL_ON_CFG_CLR_ADDR	(PLL_GLB_REG_BASE + 0x208)
#define BITS_PLL_NPLL_ON_CFG_CLR	(0xff << 9)
#define PLL_VPLL0_ON_CFG_CLR_ADDR	(PLL_GLB_REG_BASE + 0x1D8)
#define BITS_PLL_VPLL0_ON_CFG_CLR	(0xff << 9)
#define PLL_VPLL1_ON_CFG_CLR_ADDR	(PLL_GLB_REG_BASE + 0x1E4)
#define BITS_PLL_VPLL1_ON_CFG_CLR	(0xff << 9)
#define PLL_GRP_PLL_RE_OPEN_SET_ADDR	(PLL_GLB_REG_BASE + 0x234)
#define PLL_GRP_PLL_RE_OPEN_CLR_ADDR	(PLL_GLB_REG_BASE + 0x238)
#endif
