#ifndef __PMU_COMMON_H_
#define __PMU_COMMON_H_

#include <stdint.h>
#include <common/debug.h>

#define PMU_GLB_BASE_ADDR		0x02100000

#define PMU_GLB_PWR_WAIT0_ADDR		(PMU_GLB_BASE_ADDR + 0x10)

#define PMU_GLB_PWR_WAIT1_ADDR		(PMU_GLB_BASE_ADDR + 0x14)

#define PMU_GLB_PWR_WAITON0_ADDR	(PMU_GLB_BASE_ADDR + 0x18)

#define PMU_GLB_PWR_WAITON1_ADDR	(PMU_GLB_BASE_ADDR + 0x1C)

#define PMU_GLB_PWR_BYPASS_CLR_ADDR	(PMU_GLB_BASE_ADDR + 0x80)

#define PMU_GLB_PWR_STATE_ADDR		(PMU_GLB_BASE_ADDR + 0x0C)

#define PMU_GLB_SLP_EN_SET_ADDR		(PMU_GLB_BASE_ADDR + 0x6C)

#define PMU_GLB_SLP_EN_CLR_ADDR		(PMU_GLB_BASE_ADDR + 0x70)

#define PMU_GLB_CPU_SYS_SLP_REQ_ADDR	(PMU_GLB_BASE_ADDR + 0x64)
#define BIT_PMU_GLB_CPU_SYS_SLP_REQ_MASK (1 << 0)

#define PMU_GLB_PWR_BYPASS_ADDR		(PMU_GLB_BASE_ADDR + 0x8)
#define PMU_GLB_PWR_BYPASS_CPU_CLR(w)	w &= ~( 0x1 << 0)

#define PMU_GLB_RST_FRC_SW_CLR_ADDR	(PMU_GLB_BASE_ADDR + 0xF8)

#define PMU_GLB_RST_FRC_EN_SET_ADDR	(PMU_GLB_BASE_ADDR + 0xEC)
#define BIT_PMU_GLB_RST_FRC_EN_FLASH_SET (2 << 1)

#define PMU_GLB_WAKUP_SET_ADDR		(PMU_GLB_BASE_ADDR + 0x74)

#define PMU_GLB_WAKUP_CLR_ADDR		(PMU_GLB_BASE_ADDR + 0x78)

#define PMU_GLB_RST_FRC_SW_SET_ADDR	(PMU_GLB_BASE_ADDR + 0xF4)
#define BIT_PMU_GLB_RST_FRC_SW_FLASH_SET (2 << 1)

#define PMU_GLB_RST_FRC_EN_CLR_ADDR	(PMU_GLB_BASE_ADDR + 0xF0)

#define PMU_GLB_INT_RAW_ADDR		(PMU_GLB_BASE_ADDR + 0x58)

#define PMU_GLB_INT_CLR_SET_ADDR	(PMU_GLB_BASE_ADDR + 0x114)

#define PMU_GLB_CLK_FRC_EN_ADDR		(PMU_GLB_BASE_ADDR + 0x38)
#define PMU_GLB_CLK_FRC_EN_SET_ADDR		(PMU_GLB_BASE_ADDR + 0xDC)
#define PMU_GLB_CLK_FRC_SW_ADDR		(PMU_GLB_BASE_ADDR + 0x3C)
#define PMU_GLB_CLK_FRC_SW_SET_ADDR		(PMU_GLB_BASE_ADDR + 0xE4)
#define BIT_PMU_GLB_PERIPH_SYS_CLK_FRC_EN	(1 << 7)


typedef enum MODULES_ENUM {
	MODULE_GROUP1_START = 0,
	MODULE_CPU = MODULE_GROUP1_START,
	MODULE_DDR,
	MODULE_FLASH,
	MODULE_ISP,
	MODULE_MM,
	MODULE_NPU,
	MODULE_VPU,
	MODULE_PERIPH,
} MODULES_ENUM;

typedef enum SLP_EN_ENUM {
	SLP_EN_SET = 1,
	SLP_EN_CLR = 2,
} SLP_EN_ENUM;

typedef enum PWR_STATE_ENUM {
	PWR_STATE_ON = 0,
	PWR_STATE_OFF = 5,
} PWR_STATE_ENUM;
#endif
