#ifndef __VPU_SYS_H_
#define __VPU_SYS_H_
#include <sys_all_have.h>
#include <pmu.h>
#define VPU_SYS_GLB_BASE_ADDR			0x4030000
#define VPU_SYS_CLK_MUX_0_ADDR			(VPU_SYS_GLB_BASE_ADDR + 0x0)
#define VPU_SYS_CLK_EB_0_ADDR			(VPU_SYS_GLB_BASE_ADDR + 0x4)
#define BITS_VPU_SYS_CLK_EB_0			0x1
#define VPU_SYS_CLK_EB_1_ADDR			(VPU_SYS_GLB_BASE_ADDR + 0x8)
#define BITS_VPU_SYS_CLK_EB_1			0x20
#define VPU_SYS_VENC1_LPC1_SET_ADDR		(VPU_SYS_GLB_BASE_ADDR + 0x22C)
#define BIT_VPU_LPC_CFG_BUS_IDLE_EN_SET		BIT(0)
#define VPU_SYS_VENC1_LPC2_SET_ADDR		(VPU_SYS_GLB_BASE_ADDR + 0x234)
#define BIT_VPU_LPC_DATA_BUS_IDLE_EN_SET	BIT(0)
#define VPU_SYS_VENC1_LPC0_SET_ADDR		(VPU_SYS_GLB_BASE_ADDR + 0x224)
#define BIT_VPU_LPC_SLP_EN_SET			BIT(0)
#define BIT_VPU_DATA_IDLE_EN_SET		BIT(3)
#define VPU_SYS_SW_RST_0_CLR_ADDR		(VPU_SYS_GLB_BASE_ADDR + 0x120)
#define BIT_VPU_SYS_LPC_SW_RST_CLR		BIT(5)
#define VPU_SYS_VENC1_LPC0_CLR_ADDR		(VPU_SYS_GLB_BASE_ADDR + 0x228)
#define BIT_VPU_LPC_LIGHT_SLP_EN_CLR		BIT(1)
#define BIT_VPU_LPC_SLP_EN_CLR			BIT(0)
#define BIT_VPU_DATA_IDLE_EN_CLR		BIT(3)
#define VPU_SYS_VENC1_LPC1_CLR_ADDR		(VPU_SYS_GLB_BASE_ADDR + 0x230)
#define BIT_VPU_LPC_CFG_BUS_IDLE_EN_CLR		BIT(0)
#define VPU_SYS_VENC1_LPC2_CLR_ADDR		(VPU_SYS_GLB_BASE_ADDR + 0x238)
#define BIT_VPU_LPC_DATA_BUS_IDLE_EN_CLR	BIT(0)
int vpu_sys_sleep(void);
int vpu_sys_wakeup(void);
#endif
