#**********************************************************************************
#  Copyright (c) 2019-2024 Axera Semiconductor Co., Ltd. All Rights Reserved.
#
#  This source file is the property of Axera Semiconductor Co., Ltd. and
#  may not be copied or distributed in any isomorphic form without the prior
#  written consent of Axera Semiconductor Co., Ltd.
#***********************************************************************************

ifdef CONFIG_VIDEO_AXERA
obj-y += ax_vo.o
obj-y += ax_jdec_hw.o
obj-y += ax620e/ax620e_vo_common.o
obj-y += ax620e/ax620e_vo_rst_ck_mux.o
obj-y += ax620e/ax620e_vo.o
obj-y += ax620e/ax620e_vo_lite.o
obj-y += ax620e/ax620e_display_dpi.o
obj-y += ax620e/ax620e_display_mipi.o
obj-y += ax620e/ax620e_cdns_dsi.o
obj-y += ax_simple_logo.o
obj-y += ax_simple_logo_cfg.o
obj-y += panel_spi.o
endif
