/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * (C) Copyright 2023 axera <axera@axera-tech.com>
 *
 */
#ifndef	__AXCOMMON_H__
#define	__AXCOMMON_H__



#ifndef DO_DEPS_ONLY
#include "generated/ax_common_autogenerated.h"
#endif



#endif	/* __AXCOMMON_H__ */

