/**************************************************************************************************
 *
 * Copyright (c) 2019-2024 Axera Semiconductor Co., Ltd. All Rights Reserved.
 *
 * This source file is the property of Axera Semiconductor Co., Ltd. and
 * may not be copied or distributed in any isomorphic form without the prior
 * written consent of Axera Semiconductor Co., Ltd.
 *
 **************************************************************************************************/

#ifndef __AX620E_VO_LITE_REG_H
#define __AX620E_VO_LITE_REG_H

/* dpu lite register definition */
#define DPU_LITE_VERSION			0x0
#define DPU_LITE_INT_STA			0x4
#define DPU_LITE_INT_RAW			0x8
#define DPU_LITE_INT_MASK			0xC
#define DPU_LITE_INT_CLR			0x10
#define DPU_LITE_CLK_GATE_BYPASS		0x14
#define DPU_LITE_SOFT_CLR			0x18

#define DPU_LITE_DISP_UP			0x1C
#define DPU_LITE_DISP_EN			0x20
#define DPU_LITE_DISP_RESO			0x24

#define DPU_LITE_RD_FORMAT			0x28
#define DPU_LITE_RD_UV_FOR_Y			0x2C
#define DPU_LITE_RD_ADDR_Y_H			0x30
#define DPU_LITE_RD_ADDR_Y_l			0x34
#define DPU_LITE_RD_STRIDE_Y			0x38
#define DPU_LITE_RD_ADDR_C_H			0x3C
#define DPU_LITE_RD_ADDR_C_l			0x40
#define DPU_LITE_RD_STRIDE_C			0x44
#define DPU_LITE_RD_FBDC_EN			0x48
#define DPU_LITE_RD_FBDC_CTRL			0x4C
#define DPU_LITE_RD_FBDC_POS			0x50
#define DPU_LITE_RD_2YUV_EN 			0x54
#define DPU_LITE_RD_2YUV_MATRIX_00		0x58
#define DPU_LITE_RD_2YUV_MATRIX_01		0x5C
#define DPU_LITE_RD_2YUV_MATRIX_02		0x60
#define DPU_LITE_RD_2YUV_MATRIX_10		0x64
#define DPU_LITE_RD_2YUV_MATRIX_11		0x68
#define DPU_LITE_RD_2YUV_MATRIX_12		0x6C
#define DPU_LITE_RD_2YUV_MATRIX_20		0x70
#define DPU_LITE_RD_2YUV_MATRIX_21		0x74
#define DPU_LITE_RD_2YUV_MATRIX_22		0x78
#define DPU_LITE_RD_2YUV_OFFSET_00		0x7C
#define DPU_LITE_RD_2YUV_OFFSET_01		0x80
#define DPU_LITE_RD_2YUV_OFFSET_02		0x84
#define DPU_LITE_RD_2YUV_OFFSET_10		0x88
#define DPU_LITE_RD_2YUV_OFFSET_11		0x8C
#define DPU_LITE_RD_2YUV_OFFSET_12		0x90
#define DPU_LITE_RD_DECIMATION_H0		0x94
#define DPU_LITE_RD_DECIMATION_H1		0x98
#define DPU_LITE_RD_DECIMATION_H2		0x9C
#define DPU_LITE_RD_DECIMATION_H3		0xA0
#define DPU_LITE_RD_DECIMATION_H4		0xA4
#define DPU_LITE_RD_DECIMATION_H5		0xA8
#define DPU_LITE_RD_DECIMATION_H6		0xAC
#define DPU_LITE_RD_2YUV_CTRL			0xB0

#define DPU_LITE_MOUSE_CTRL			0xB4
#define DPU_LITE_MOUSE_POS			0xB8
#define DPU_LITE_MOUSE_RESO			0xBC
#define DPU_LITE_MOUSE_FORMAT			0xC0
#define DPU_LITE_MOUSE_UV_FOR_Y			0xC4
#define DPU_LITE_MOUSE_2YUV_EN			0xC8
#define DPU_LITE_MOUSE_2YUV_MATRIX_00		0xCC
#define DPU_LITE_MOUSE_2YUV_MATRIX_01		0xD0
#define DPU_LITE_MOUSE_2YUV_MATRIX_02		0xD4
#define DPU_LITE_MOUSE_2YUV_MATRIX_10		0xD8
#define DPU_LITE_MOUSE_2YUV_MATRIX_11		0xDC
#define DPU_LITE_MOUSE_2YUV_MATRIX_12		0xE0
#define DPU_LITE_MOUSE_2YUV_MATRIX_20		0xE4
#define DPU_LITE_MOUSE_2YUV_MATRIX_21		0xE8
#define DPU_LITE_MOUSE_2YUV_MATRIX_22		0xEC
#define DPU_LITE_MOUSE_2YUV_OFFSET_00		0xF0
#define DPU_LITE_MOUSE_2YUV_OFFSET_01		0xF4
#define DPU_LITE_MOUSE_2YUV_OFFSET_02		0xF8
#define DPU_LITE_MOUSE_2YUV_OFFSET_10		0xFC
#define DPU_LITE_MOUSE_2YUV_OFFSET_11		0x100
#define DPU_LITE_MOUSE_2YUV_OFFSET_12		0x104
#define DPU_LITE_MOUSE_2YUV_DECIMATION_H0	0x108
#define DPU_LITE_MOUSE_2YUV_DECIMATION_H1	0x10C
#define DPU_LITE_MOUSE_2YUV_DECIMATION_H2	0x110
#define DPU_LITE_MOUSE_2YUV_DECIMATION_H3	0x114
#define DPU_LITE_MOUSE_2YUV_DECIMATION_H4	0x118
#define DPU_LITE_MOUSE_2YUV_DECIMATION_H5	0x11C
#define DPU_LITE_MOUSE_2YUV_DECIMATION_H6	0x120
#define DPU_LITE_MOUSE_2YUV_CTRL		0x124
#define DPU_LITE_MOUSE_ADDR_H			0x128
#define DPU_LITE_MOUSE_ADDR_L		        0x12C
#define DPU_LITE_MOUSE_STRIDE			0x130
#define DPU_LITE_MOUSE_ALPHA			0x134
#define DPU_LITE_MOUSE_PIXEL_Y			0x138
#define DPU_LITE_MOUSE_PIXEL_U		 	0x13C
#define DPU_LITE_MOUSE_PIXEL_V			0x140
#define DPU_LITE_MOUSE_INV_EN			0x144
#define DPU_LITE_MOUSE_INV_THR_Y		0x148
#define DPU_LITE_MOUSE_INV_THR_U		0x14C
#define DPU_LITE_MOUSE_INV_THR_V		0x150
#define DPU_LITE_MOUSE_INV_PIXEL_Y		0x154
#define DPU_LITE_MOUSE_INV_PIXEL_U		0x158
#define DPU_LITE_MOUSE_INV_PIXEL_V		0x15C

#define DPU_LITE_DISP_2RGB_CTRL			0x160
#define DPU_LITE_DISP_2RGB_MATRIX_00		0x164
#define DPU_LITE_DISP_2RGB_MATRIX_01		0x168
#define DPU_LITE_DISP_2RGB_MATRIX_02		0x16C
#define DPU_LITE_DISP_2RGB_MATRIX_10		0x170
#define DPU_LITE_DISP_2RGB_MATRIX_11		0x174
#define DPU_LITE_DISP_2RGB_MATRIX_12		0x178
#define DPU_LITE_DISP_2RGB_MATRIX_20		0x17C
#define DPU_LITE_DISP_2RGB_MATRIX_21		0x180
#define DPU_LITE_DISP_2RGB_MATRIX_22		0x184
#define DPU_LITE_DISP_2RGB_OFFSET_00		0x188
#define DPU_LITE_DISP_2RGB_OFFSET_01		0x18C
#define DPU_LITE_DISP_2RGB_OFFSET_02		0x190
#define DPU_LITE_DISP_2RGB_OFFSET_10		0x194
#define DPU_LITE_DISP_2RGB_OFFSET_11		0x198
#define DPU_LITE_DISP_2RGB_OFFSET_12		0x19C

#define DPU_LITE_CLIP_EN			0x1A0
#define DPU_LITE_CLIP_GAIN0			0x1A4
#define DPU_LITE_CLIP_GAIN1			0x1A8
#define DPU_LITE_CLIP_GAIN2			0x1AC
#define DPU_LITE_CLIP_OFFSET_00			0x1B0
#define DPU_LITE_CLIP_OFFSET_01			0x1B4
#define DPU_LITE_CLIP_OFFSET_02			0x1B8
#define DPU_LITE_CLIP_OFFSET_10			0x1Bc
#define DPU_LITE_CLIP_OFFSET_11			0x1C0
#define DPU_LITE_CLIP_OFFSET_12			0x1C4
#define DPU_LITE_CLIP_RANGE_00			0x1C8
#define DPU_LITE_CLIP_RANGE_01			0x1CC
#define DPU_LITE_CLIP_RANGE_10			0x1D0
#define DPU_LITE_CLIP_RANGE_11			0x1D4
#define DPU_LITE_CLIP_RANGE_20			0x1D8
#define DPU_LITE_CLIP_RANGE_21			0x1DC

#define DPU_LITE_DITHER_EN			0x1E0
#define DPU_LITE_DITHER_UP			0x1E4
#define DPU_LITE_DITHER_SEED_R			0x1E8
#define DPU_LITE_DITHER_PMASK_R			0x1EC
#define DPU_LITE_DITHER_SEED_G			0x1F0
#define DPU_LITE_DITHER_PMASK_G			0x1F4
#define DPU_LITE_DITHER_SEED_B			0x1F8
#define DPU_LITE_DITHER_PMASK_B			0x1FC
#define DPU_LITE_DITHER_OUT_ACC			0x200

#define DPU_LITE_BAD_PIXEL			0x204
#define DPU_LITE_OUT_MODE			0x208
#define DPU_LITE_DISP_CLK			0x20C
#define DPU_LITE_DISP_HSYNC			0x210
#define DPU_LITE_DISP_VSYNC			0x214
#define DPU_LITE_DISP_SYNC			0x218
#define DPU_LITE_DISP_HHALF			0x21C
#define DPU_LITE_DISP_VTOTAL			0x220
#define DPU_LITE_DISP_POLAR			0x224
#define DPU_LITE_DISP_FORMAT			0x228
#define DPU_LITE_BT_MODE			0x22C

#define DPU_LITE_PIN_SRC_SEL0			0x230
#define DPU_LITE_PIN_SRC_SEL1			0x234
#define DPU_LITE_PIN_SRC_SEL2			0x238
#define DPU_LITE_PIN_SRC_SEL3			0x23C
#define DPU_LITE_PIN_SRC_SEL4			0x240

#define DPU_LITE_AXI_EN				0x244
#define DPU_LITE_AXI_CNT			0x248
#define DPU_LITE_AXI_OSD			0x24C
#define DPU_LITE_AXI_QOS			0x250

#define DPU_LITE_DEBUG_DUMMY_EN			0x254
#define DPU_LITE_DEBUG_DUMMY_IN			0x258
#define DPU_LITE_DEBUG_DUMMY_OUT		0x25C
#define DPU_LITE_CMD_REQ			0x260
#define DPU_LITE_DEBUG_DISP_TOP			0x264
#define DPU_LITE_DEBUG_JOIN_MOUSE		0x268

/*interrupt*/
#define DPU_INT_DISP_EOF			BIT(2)
#define DPU_INT_DISP_SOF			BIT(3)
#define DPU_INT_AXI_RERR			BIT(5)
#define DPU_INT_DISP_UNDER			BIT(6)

#define DISP_LITE_UPDATE			BIT(1)
#define DPU_LITE_AXI_QOS_VAL_DEFAULT            0x6073
/* dpu register definition end */

#endif /* __AX620E_VO_LITE_REG_H */
