#!/bin/sh

ubiattach /dev/ubi_ctrl -m 4
mount -t ubifs /dev/ubi1_0 /param
mkdir -p /opt/data/AXSyslog/kernel

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#

for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

/soc/scripts/usb-acm.sh usb2
chmod 755 /soc/scripts/auto_load_all_drv.sh
/soc/scripts/auto_load_all_drv.sh
hwclock -s
/etc/init.d/axsyslogd start
/etc/init.d/axklogd start
mdev -s
mount -t pstore pstore /sys/fs/pstore
/soc/scripts/interrupt_affinity.sh
