#!/bin/sh

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

mknod /dev/null c 1 3

export PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin"
export LD_LIBRARY_PATH="/usr/local/lib:/usr/lib"

for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

if [ -f /usr/bin/swupdate.sh ]; then
	/usr/bin/swupdate.sh
fi
